version: '3'

services:
  order-service:
    image: ahmeddhibi/order-service:latest
    container_name: order-service
    ports:
      - 8084:8084
    networks:
      - global-network
      - bank-network
    environment:
      SPRING_APPLICATION_NAME: order
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_bank:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: azerty
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8084
      CART_SERVICE_URL: http://cart-service:8081/cart/
      INVENTORY_SERVICE_URL: http://inventory-service:8083/inventory/reserve
      PAYMENT_SERVICE_URL: http://payment-service:8085/payment/process
      SHIPPING_SERVICE_URL: http://shipping-service:8090/shipping/schedule
      MAIL_SERVICE_URL: http://mail-service:8091/mail/send
    depends_on:
      bank-service-db_bank-1:
        condition: service_healthy
networks:
  bank-network:
    external: true
  global-network:
    external: true

