version: '3'

services:
  pricing-service:
    image: ahmeddhibi/pricing-service:latest
    container_name: pricing-service
    ports:
      - 8086:8086
    networks:
      - global-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-service-db_bank-1:5432/pricing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: azerty
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_APPLICATION_NAME: pricing-service
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      CATALOG_SERVICE_URL: "http://catalog-service:8082"
      KEYCLOAK_REALM: ecommerce-platform
      KEYCLOAK_AUTH_SERVER_URL: http://92.222.24.59:8080/realms/ecommerce-platform
      KEYCLOAK_CLIENT_ID: princing_client
      KEYCLOAK_CLIENT_SECRET: "tHBc3gcqkmzjIHitrQIEcOlzYThjuDj2"
      KEYCLOAK_BEARER_ONLY: true

networks:
  global-network:
    external: true
