server.port=8090
spring.application.name=shipping

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db-shipping
spring.datasource.username=postgres
spring.datasource.password=azerty
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# External Service URL
shipping.service.url=http://localhost:8084/order
