server:
  port: 8082

keycloak:
  realm: ecommerce-platform
  auth-server-url: http://92.222.24.59:8080/realms/ecommerce-platform
  resource: catalog_client
  credentials:
    secret: "IhUhTtmwWyiyj5IZuquvwKAnwFDWmx8i"
  bearer-only: true
  public-client: false
  ssl-required: external

spring:
  security:
    oauth2:
      client:
        registration:
          catalog_client:
            client-id: catalog_client
            client-secret: "IhUhTtmwWyiyj5IZuquvwKAnwFDWmx8i"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          catalog_client:
            authorization-uri: http://92.222.24.59:8080/realms/ecommerce-platform/protocol/openid-connect/auth
            token-uri: http://92.222.24.59:8080/realms/ecommerce-platform/protocol/openid-connect/token
            user-info-uri: http://92.222.24.59:8080/realms/ecommerce-platform/protocol/openid-connect/userinfo