name: CI/CD Job for the reviews service

on:
  push:
    branches: 
      - reviews
    paths:
      - 'reviews/**'
  pull_request:
    branches: 
      - reviews

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./reviews

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Specify the version of .NET you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the app
      run: dotnet build --configuration Release

    - name: Publish the app
      run: dotnet publish --configuration Release --output ./publish

    - name: List published directory contents
      run: ls -al ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: order-service
        path: ./publish

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reviews-service:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/reviews-service:latest
  deploy:
    needs: build 

    runs-on: ubuntu-latest 

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Add Server to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DEPLOYMENT_MACHINE_IP }} >> ~/.ssh/known_hosts

    - name: Create deployment directory structure on VPS
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "mkdir -p ~/soa-ecomm/reviews-service"
        
    - name: Check and clean up docker-compose in reviews-service folder
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "if [ -f ~/soa-ecomm/reviews-service/docker-compose.yml ]; then rm ~/soa-ecomm/reviews-service/docker-compose.yml; fi"

    - name: Check and stop order-service container if running
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "if docker ps --format '{{.Names}}' | grep -q '^reviews-service$'; then docker stop reviews-service && docker rm reviews-service; fi"

    - name: Check and create global network if not exists
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "if ! docker network ls --format '{{.Name}}' | grep -q '^global-network$'; then docker network create global-network; fi"

    - name: Transfer docker-compose to VPS
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" scp docker-compose.yml \
        ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }}:~/soa-ecomm/reviews-service/docker-compose.yml

    - name: Check the status of db_bank container
      id: db_check
      run: |
        STATUS=$(sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "if docker ps --filter 'name=bank-service-db_bank-1' --filter 'health=healthy' --format '{{.Names}}' | grep -q '^bank-service-db_bank-1$'; then \
          echo 'healthy'; \
        else \
          echo 'unhealthy'; \
        fi")
        echo "db_status=$STATUS" >> $GITHUB_ENV

    - name: Deploy reviews-service
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "if [ \"${{ env.db_status }}\" = 'healthy' ]; then \
          echo 'Starting only reviews-service'; \
          cd ~/soa-ecomm/reviews-service && docker-compose up -d reviews-service; \
        else \
          echo 'Starting all services'; \
          cd ~/soa-ecomm/reviews-service && docker-compose up -d; \
        fi"

    - name: Check deployment status
      run: |
        sshpass -p "${{ secrets.MACHINE_PASSWORD }}" ssh ${{ secrets.MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
        "cd ~/soa-ecomm/reviews-service && docker-compose ps && docker volume ls && docker network ls && echo 'System Resources:' && df -h && free -h"